### ISSUE TITLE
Dll function definitions and structs

### ISSUE THREAD

**Issue by PAEz** [proog128/jswin#7]
Would it be possible to make it so that I can declare a dll functions parameter to be a struct using "s" but then later be able to pass null as that value and internally you make that value equal 0?
Its just that some times a parameter expects a pointer to a struct but it may be optional, in which case you can pass a 0 to say there isnt one.
Right now Im having to make two versions of function calls, one the one you'd expect with structs and the other with "i"s that I pass the pointer myself to so that I can pass 0 if I want.

**Comment by proog128** [comment]
There should be definitely the possibility to specify null for structs and strings. I have added that to jswin. Moreover, you can now specify the return type of a function as `int`, `unsigned int`, and `void`. Default is `int`, otherwise I would break a lot of your code. However, at some point in the future I would like to add the return type to the signature string, maybe as first character. For now I will stick to the solution with extra parameter :smiley:

**Comment by PAEz** [comment]
Sweet, and the return type aswell, even better ;)

If you want to change the parameter formatting, then do it, Ill live.
Be no hassle to go around sticking an i everywhere, plus for the big dll list Ill just use code.  One of the reason I like to make everything into an object is for things like this.
Plus Im redoing a bunch of stuff to go with AutoItX anyway, so now would be a great time for things to change.
